name: Auto-Merge Registry PRs
on:
  workflow_run:
    workflows: [ "Validate Index", "Link Check" ]
    types: [ completed ]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find PR from bot branch
        id: pr
        run: |
          gh pr list --state open --json number,headRefName,files \
            | jq -r '.[] | select(.headRefName=="bot/registry-sync") | .number' | head -n1 > pr.txt || true
          PR=$(cat pr.txt || true)
          if [ -z "$PR" ]; then echo "no PR"; exit 0; fi
          echo "pr=$PR" >> $GITHUB_OUTPUT
        env: { GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
      - name: Enable auto-merge (squash)
        if: steps.pr.outputs.pr
        run: gh pr merge $PR --squash --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ steps.pr.outputs.pr }}
