name: Build & Deploy Catalog
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency: { group: pages, cancel-in-progress: true }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { submodules: false }
      - name: Build dist
        run: |
          set -e
          mkdir -p dist/site dist/registry
          rsync -a site/ dist/site/
          curl -fsSL https://mcp-accelerator.github.io/mcp-registry/servers.index.json \
            -o dist/registry/servers.index.json
          jq . dist/registry/servers.index.json >/dev/null
      - uses: actions/upload-pages-artifact@v3
        with: { name: github-pages, path: dist }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
