name: Link Check
on:
  pull_request:
    paths:
      - '**/*.md'
      - 'site/**/*.html'
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: false
      - uses: lycheeverse/lychee-action@v2
        with:
          args: "--config .lychee.toml".