name: Link Check
on:
  pull_request:
    paths: ['**/*.md','site/**/*.html']

permissions:
  contents: read

concurrency:
  group: lychee-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: false
      - uses: lycheeverse/lychee-action@v2
        with:
          args: "--no-progress --max-redirects 5 --accept 200,206,301,302,307,308,429 --config .lychee.toml ."
          format: markdown
          output: lychee/out.md
          jobSummary: true
