name: Link Check
on:
  pull_request:
    paths:
      - '**/*.md'
      - 'site/**/*.html'
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Run lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config .lychee.toml .
          fail: true
          failIfEmpty: true
          format: markdown
          output: lychee/out.md
          jobSummary: true
