name: Validate Index
on:
  pull_request:
    paths: ['registry/**','schema/**','servers/**']
  push:
    branches: [ main ]
    paths: ['registry/**','schema/**','servers/**']

permissions:
  contents: read

jobs:
  ajv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install ajv-cli
        run: npm -g i ajv-cli@5
      - name: Validate manifests (draft-07)
        run: |
          ajv validate --spec=draft7 -s schema/mcp-server.schema.json -d 'servers/*/mcp-server.json' --strict=false || true
      - name: Validate index (draft-07)
        run: |
          test -s registry/servers.index.json
          jq '.servers // .' registry/servers.index.json > .tmp.index.json
          ajv validate --spec=draft7 -s schema/mcp-server-index.schema.json -d .tmp.index.json --strict=false
          rm -f .tmp.index.json
