name: Validate External Index
on:
  pull_request:
    paths: ['.github/workflows/validate-index.yml','site/**','tools/validate-external-index.sh']
  push:
    branches: [ main ]
    paths:   ['.github/workflows/validate-index.yml','site/**','tools/validate-external-index.sh']

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Validate external registry index
        run: tools/validate-external-index.sh
